const KEY='churchRequestFormsSubmissionDataV1';
const data=JSON.parse(localStorage.getItem(KEY)||'{"purchases":[],"invoices":[],"requests":[]}');
const save=()=>{localStorage.setItem(KEY,JSON.stringify(data));render()};
const money=n=>Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nextNo=(prefix,arr)=>`${prefix}-${new Date().getFullYear()}-${String(arr.length+1).padStart(3,'0')}`;
document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.view).classList.add('active')});
const setDates=()=>document.querySelectorAll('input[type=date]').forEach(i=>{if(!i.value)i.value=new Date().toISOString().slice(0,10)});setDates();
purchaseForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.purchases.unshift({id:Date.now(),date:f.get('date'),vendor:f.get('vendor'),item:f.get('item'),amount:+f.get('amount'),payment:f.get('payment'),reference:f.get('reference'),notes:f.get('notes')});e.target.reset();setDates();save()};
invoiceForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),qty=+f.get('qty'),price=+f.get('price');data.invoices.unshift({id:Date.now(),number:nextNo('INV',data.invoices),date:f.get('date'),due:f.get('due'),billTo:f.get('billTo'),description:f.get('description'),qty,price,total:qty*price,notes:f.get('notes')});e.target.reset();setDates();save()};
requestForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.requests.unshift({id:Date.now(),number:nextNo('REQ',data.requests),requester:f.get('requester'),department:f.get('department'),date:f.get('date'),amount:+f.get('amount'),description:f.get('description'),reason:f.get('reason'),status:'Pending'});e.target.reset();setDates();save()};
function updateStatus(id,value){const r=data.requests.find(x=>x.id===id);if(r){r.status=value;save()}}window.updateStatus=updateStatus;
function printInvoice(id){const i=data.invoices.find(x=>x.id===id);if(!i)return;const w=window.open('','_blank');w.document.write(`<html><head><title>${i.number}</title></head><body style="font-family:Arial;padding:40px"><h1>Church Request Forms Submission</h1><h2>Invoice ${i.number}</h2><p><b>Date:</b> ${i.date}</p><p><b>Due:</b> ${i.due}</p><p><b>Bill To:</b> ${esc(i.billTo)}</p><hr><p><b>Description:</b> ${esc(i.description)}</p><p><b>Quantity:</b> ${i.qty}</p><p><b>Unit Price:</b> $${money(i.price)}</p><h3>Total: $${money(i.total)}</h3><p><b>Notes:</b> ${esc(i.notes||'')}</p></body></html>`);w.document.close();w.print()}window.printInvoice=printInvoice;
function render(){purchaseCount.textContent=data.purchases.length;invoiceCount.textContent=data.invoices.length;pendingCount.textContent=data.requests.filter(r=>r.status==='Pending').length;approvedCount.textContent=data.requests.filter(r=>r.status==='Approved').length;purchaseRows.innerHTML=data.purchases.map(p=>`<tr><td>${p.date}</td><td>${esc(p.vendor)}</td><td>${esc(p.item)}</td><td>$${money(p.amount)}</td><td>${esc(p.reference||'')}</td></tr>`).join('')||'<tr><td colspan="5">No purchases recorded.</td></tr>';invoiceRows.innerHTML=data.invoices.map(i=>`<tr><td>${i.number}</td><td>${i.date}</td><td>${esc(i.billTo)}</td><td>$${money(i.total)}</td><td><button class="small-btn" onclick="printInvoice(${i.id})">Print</button></td></tr>`).join('')||'<tr><td colspan="5">No invoices created.</td></tr>';requestRows.innerHTML=data.requests.map(r=>`<tr><td>${r.number}</td><td>${r.date}</td><td>${esc(r.requester)}</td><td>${esc(r.department||'')}</td><td>$${money(r.amount)}</td><td class="status">${r.status}</td><td><select onchange="updateStatus(${r.id},this.value)"><option ${r.status==='Pending'?'selected':''}>Pending</option><option ${r.status==='Approved'?'selected':''}>Approved</option><option ${r.status==='Rejected'?'selected':''}>Rejected</option></select></td></tr>`).join('')||'<tr><td colspan="7">No requests submitted.</td></tr>';const activity=[...data.requests.slice(0,3).map(x=>({t:`Request ${x.number} — ${x.status}`,d:x.date})),...data.invoices.slice(0,3).map(x=>({t:`Invoice ${x.number} — $${money(x.total)}`,d:x.date})),...data.purchases.slice(0,3).map(x=>({t:`Purchase — ${x.vendor} — $${money(x.amount)}`,d:x.date}))].sort((a,b)=>String(b.d).localeCompare(String(a.d))).slice(0,6);recentActivity.innerHTML=activity.length?activity.map(a=>`<p><strong>${esc(a.t)}</strong><br><small>${a.d}</small></p>`).join(''):'No activity yet.'}
exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='church-request-data.json';a.click();URL.revokeObjectURL(a.href)};render();
